logs:
  delete_logs: true
  actually_get_logs: true
robot:
  ip: 'roborio-1751-frc.local'
  username: 'lvuser'
log_settings:
  repo_path:  'RA17_LogFileArchive'
  local_path: 'RA17_LogFileArchive/logs/'
  remote_path: 'logs/'
