logs:
  delete_logs: true
  actually_get_logs: true
robot:
  ip: 'roborio-1751-frc.local'
  username: 'lvuser'
log_settings:
  repo_path:  'RA21_LogFileArchive'
  local_path: 'RA21_LogFileArchive/logs/'
  ftp_path:   '/home/lvuser/'
  remote_path: 'logs/'
