version: "3"

volumes:
  bundle_cache:

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    env_file:
      - ./vars.env
    ports:
      - "4567:4567"
    volumes:
      - .:/app:delegated
      - bundle_cache:/bundle
